### ISSUE TITLE
Parse and validate usages of extensions

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/extensions-catalog#40]
#### Reason/Context
Whenever an extension is in use in the AsyncAPI specification it should be possible to validate the extension data against the JSON Schema [inside the extension](https://github.com/asyncapi/extensions-catalog/blob/aacc2688751d8ba4204e949f9eaefff4c2f1bf67/schema.json#L63).

This is needed to validate extensions in our [parser-js](github.com/asyncapi/parser-js) as well as other libraries.

Blocked by https://github.com/asyncapi/extensions-catalog/issues/39

**Comment by smoya** [comment]
This will be closed by https://github.com/asyncapi/extensions-catalog/issues/78
