### ISSUE TITLE
Create extension UI components 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/extensions-catalog#43]
#### Reason/Context
We should provide extension UI components that make it easy to display publically known extensions in applications.

Blocked by https://github.com/asyncapi/extensions-catalog/issues/45

**Comment by derberg** [comment]
you mean like a component for our react component?, so "official" extensions are not displayed as "extensions" but as normal properties, basing on their JSON Schema?

**Comment by magicmatatjahu** [comment]
I think that [this issue](https://github.com/asyncapi/asyncapi-react/issues/279) is related.

**Comment by jonaslagoni** [comment]
The thoughts I got when it was brought up in the SIG meeting, was UI components for rendering the different extensions available. Not rendering used extensions in the AsyncAPI document.
